

--==>> 2022-07-10(19:12) 이윤태 추가
INSERT INTO USER_DSTN(USER_DSTN_CD) VALUES(USER_DSTN_SEQ.NEXTVAL);

INSERT INTO USER_PLUS(USER_PLUS_CD, USER_DSTN_CD, SSN, MRG_CD, CHILD_CD, FML_CD
                    , PET_CD, CAR_CD, HOUSE_CD, AREA_SEC_CD, JOB_SEC_CD)
VALUES(USER_PLUS_SEQ.NEXTVAL, 1019, '970101-1', 1, 1, 1, 1, 1, 1, 1, 1);

INSERT INTO USER_INFO(USER_ID, USER_DSTN_CD, USER_NAME, USER_PW, USER_TEL, USER_DATE)
VALUES('test19@test.com', 1019, '홍길동', CRYPTPACK.ENCRYPT('qwerty123@', '123456'), '010-1111-1111', TO_DATE('2022-02-01', 'YYYY-MM-DD'));


INSERT INTO USER_DSTN(USER_DSTN_CD) VALUES(USER_DSTN_SEQ.NEXTVAL);

INSERT INTO USER_PLUS(USER_PLUS_CD, USER_DSTN_CD, SSN, MRG_CD, CHILD_CD, FML_CD
                    , PET_CD, CAR_CD, HOUSE_CD, AREA_SEC_CD, JOB_SEC_CD)
VALUES(USER_PLUS_SEQ.NEXTVAL, 1020, '970111-1', 1, 1, 1, 1, 1, 1, 1, 1);

INSERT INTO USER_INFO(USER_ID, USER_DSTN_CD, USER_NAME, USER_PW, USER_TEL, USER_DATE)
VALUES('test20@test.com', 1020, '문선민', CRYPTPACK.ENCRYPT('qwerty123@', '123456'), '010-1111-1111', TO_DATE('2022-02-05', 'YYYY-MM-DD'));


INSERT INTO USER_DSTN(USER_DSTN_CD) VALUES(USER_DSTN_SEQ.NEXTVAL);

INSERT INTO USER_PLUS(USER_PLUS_CD, USER_DSTN_CD, SSN, MRG_CD, CHILD_CD, FML_CD
                    , PET_CD, CAR_CD, HOUSE_CD, AREA_SEC_CD, JOB_SEC_CD)
VALUES(USER_PLUS_SEQ.NEXTVAL, 1021, '950111-1', 1, 2, 3, 1, 1, 2, 1, 1);

INSERT INTO USER_INFO(USER_ID, USER_DSTN_CD, USER_NAME, USER_PW, USER_TEL, USER_DATE)
VALUES('test21@test.com', 1021, '손준호', CRYPTPACK.ENCRYPT('qwerty123@', '123456'), '010-1111-1111', TO_DATE('2022-02-05', 'YYYY-MM-DD'));


INSERT INTO USER_DSTN(USER_DSTN_CD) VALUES(USER_DSTN_SEQ.NEXTVAL);

INSERT INTO USER_PLUS(USER_PLUS_CD, USER_DSTN_CD, SSN, MRG_CD, CHILD_CD, FML_CD
                    , PET_CD, CAR_CD, HOUSE_CD, AREA_SEC_CD, JOB_SEC_CD)
VALUES(USER_PLUS_SEQ.NEXTVAL, 1022, '870111-1', 1, 1, 1, 1, 1, 1, 1, 1);

INSERT INTO USER_INFO(USER_ID, USER_DSTN_CD, USER_NAME, USER_PW, USER_TEL, USER_DATE)
VALUES('test22@test.com', 1022, '홍정호', CRYPTPACK.ENCRYPT('qwerty123@', '123456'), '010-1111-1111', TO_DATE('2022-02-15', 'YYYY-MM-DD'));

COMMIT;


CREATE OR REPLACE VIEW POST_REPT_VIEW
AS
SELECT PR.POST_REPT_CD, PR.POST_REPT_DATE, P.POST_CD, PR.USER_DSTN_CD "REPT_USER_DSTN_CD"
     , DECODE(AP.AD_POST_REPT_CD, NULL, '-', AP.AD_POST_REPT_CD) "AD_POST_REPT_CD"
     , DECODE(AP.AD_POST_REPT_CD, NULL, '-', AP.CNFM_CD) "CNFM_CD"
     , DECODE(AP.AD_POST_REPT_CD, NULL, '-', C.CNFM_RESULT) "CNFM_RESULT"
     , DECODE(AP.AD_POST_REPT_CD, NULL, '-', AP.AD_CD) "AD_CD"
     , DECODE(AP.AD_POST_REPT_CD, NULL, TO_DATE('1111-11-11','YYYY-MM-DD') , AP.AD_POST_REPT_DATE) "AD_POST_REPT_DATE"
     , P.OPINION, PR.REPT_CATE_CD, RC.REPT_CATE_NAME 
     , DECODE(PR.REPT_CATE_CD, 5, PRD.POST_REPT_DTL_CONT, '-') "POST_REPT_DTL_CONT"
     , P.USER_DSTN_CD, P.POST_TITLE, P.POST_DATE
FROM POST_REPT PR
FULL OUTER JOIN AD_POST_REPT AP
  ON PR.POST_REPT_CD = AP.POST_REPT_CD
LEFT JOIN POST P 
  ON PR.POST_CD = P.POST_CD
LEFT JOIN CNFM C
  ON AP.CNFM_CD = C.CNFM_CD
LEFT JOIN REPT_CATE RC
  ON PR.REPT_CATE_CD = RC.REPT_CATE_CD
LEFT JOIN POST_REPT_DTL PRD
  ON AP.POST_REPT_CD = PRD.POST_REPT_CD;


--==>> View POST_REPT_VIEW이(가) 생성되었습니다.



CREATE OR REPLACE VIEW CMNT_REPT_VIEW
AS
SELECT CR.CMNT_REPT_CD, CR.CMNT_REPT_DATE, CM.CMNT_CD, CR.USER_DSTN_CD "REPT_USER_DSTN_CD"
     , DECODE(AC.AD_CMNT_REPT_CD, NULL , '-', AC.AD_CMNT_REPT_CD) "AD_CMNT_REPT_CD"
     , DECODE(AC.AD_CMNT_REPT_CD, NULL , '-', AC.CNFM_CD) "CNFM_CD"
     , DECODE(AC.AD_CMNT_REPT_CD, NULL , '-', C.CNFM_RESULT) "CNFM_RESULT"
     , DECODE(AC.AD_CMNT_REPT_CD, NULL , '-', AC.AD_CD) "AD_CD"
     , DECODE(AC.AD_CMNT_REPT_DATE, NULL , TO_DATE('1111-11-11','YYYY-MM-DD'), AC.AD_CMNT_REPT_DATE) "AD_CMNT_REPT_DATE"
     , CR.REPT_CATE_CD, RC.REPT_CATE_NAME 
     , DECODE(CR.REPT_CATE_CD, 5, CRD.CMNT_REPT_DTL_CONT, '-') "CMNT_REPT_DTL_CONT"
     , CM.POST_CD, P.USER_DSTN_CD "POST_REG_USER"
     , CM.USER_DSTN_CD, CM.CMNT_CONT, CM.CMNT_DATE
FROM CMNT_REPT CR
FULL OUTER JOIN AD_CMNT_REPT AC
  ON CR.CMNT_REPT_CD = AC.CMNT_REPT_CD
LEFT JOIN CMNT CM
  ON CR.CMNT_CD = CM.CMNT_CD
LEFT JOIN POST P 
  ON CM.POST_CD = P.POST_CD
LEFT JOIN CNFM C
  ON AC.CNFM_CD = C.CNFM_CD
LEFT JOIN REPT_CATE RC
  ON CR.REPT_CATE_CD = RC.REPT_CATE_CD
LEFT JOIN CMNT_REPT_DTL CRD
  ON AC.CMNT_REPT_CD = CRD.CMNT_REPT_CD;



--==>> View CMNT_REPT_VIEW이(가) 생성되었습니다.

